INSERT INTO PARENTS (EMAIL, NICKNAME, ROLE) VALUES ('parent1@kakao.com', '보호자1', 'ROLE_PARENT')
INSERT INTO PARENTS (EMAIL, NICKNAME, ROLE) VALUES ('parent2@kakao.com', '보호자2', 'ROLE_PARENT')
INSERT INTO PARENTS (EMAIL, NICKNAME, ROLE) VALUES ('parent3@kakao.com', '보호자3', 'ROLE_PARENT')
